sudo: required
services:
  - docker

before_install:
  - docker build -t irsital/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run irsital/react-test npm test -- --coverage

after_success:
  - docker build -t irsital/multi-client ./client
  - docker build -t irsital/multi-nginx ./nginx
  - docker build -t irsital/multi-server ./server
  - docker build -t irsital/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push irsital/multi-client
  - docker push irsital/multi-nginx
  - docker push irsital/multi-server
  - docker push irsital/multi-worker
